### ISSUE TITLE
Installing with version 5 fails

### ISSUE THREAD

**Issue by Turkzilla** [elastic/elasticsearch-migration#121]
```bash
$ ./bin/elasticsearch-plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.4/elasticsearch-migration-2.0.4.zip

-> Downloading https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.4/elasticsearch-migration-2.0.4.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: property [elasticsearch.version] is missing for plugin [elasticsearch-migration]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:186)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:713)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:792)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Comment by Turkzilla** [comment]
Nevermind, saw the warning in the README now:

> Important | It will run on Elasticsearch versions 2.3.x and 2.4.x only.

However, the error/failure could be more in the line of informing user for a version mis-match.
