### ISSUE TITLE
Cannot read property '0' of null Error when selecting Ignore Closed indices option

### ISSUE THREAD

**Issue by russorat** [elastic/elasticsearch-migration#35]
Works fine when the box is unchecked.

<img width="1092" alt="elasticsearch_migration_checker_v0_14" src="https://cloud.githubusercontent.com/assets/4805997/10799551/a3f11162-7d6a-11e5-9820-8972e07e4834.png">

**Comment by clintongormley** [comment]
@russorat What browser are you using? Could you try again with the console window open, and paste the contents into a comment here please?

**Comment by walkeran** [comment]
Also happening to me -- using Chrome. Can confirm that it's only when checking "Ignore closed indices".

```
Unhandled rejection TypeError: Cannot read property '0' of null
    at Object.get_key (http://myhost:9200/_plugin/migration/js/registry.js:31:36)
    at http://myhost:9200/_plugin/migration/js/main.js:86:22
    at forall (http://myhost:9200/_plugin/migration/js/main.js:6:17)
    at check_indices (http://myhost:9200/_plugin/migration/js/main.js:72:7)
    at n (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:31:354)
    at e._settlePromiseFromHandler (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:30:5642)
    at e._settlePromiseAt (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:30:6911)
    at e._settlePromises (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:30:8776)
    at r._drainQueue (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:29:3690)
    at r._drainQueues (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:29:3751)
    at MutationObserver.drainQueues (http://myhost:9200/_plugin/migration/js/bluebird/bluebird.min.js:29:1182)
```

**Comment by bstascavage** [comment]
I also have encountered this while using Chrome

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch-migration/commit/156929b5ba9432e161362abdf62c448046867c76
